name: Build TWRP for Samsung A145P

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 20480
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Check Out Device Tree
        uses: actions/checkout@v4  # <--- اینو از v3 بکن v4
        with:
          path: device/samsung/a145p
          lfs: true


      - name: Set up Git LFS manually
        run: |
          cd device/samsung/a145p
          git lfs pull

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf libncurses5-dev libncurses-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc zip zlib1g-dev python3 python3-pip


      - name: Install Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Initialize TWRP Source
        run: |
          mkdir -p workspace
          cd workspace
          git config --global user.name "Behrooz140"
          git config --global user.email "behrooz@example.com"
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1 --depth=1

      - name: Sync Sources
        run: |
          cd workspace
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Copy Device Tree
        run: |
          mkdir -p workspace/device/samsung/a145p
          cp -r device/samsung/a145p/* workspace/device/samsung/a145p/


      - name: Build TWRP
        run: |
          cd workspace
          export CCACHE_EXEC=$(which ccache)
          export USE_CCACHE=1
          source build/envsetup.sh
          lunch twrp_a145p-eng || lunch omni_a145p-eng
          mka recoveryimage -j$(nproc --all)

      - name: Upload Recovery Image
        uses: actions/upload-artifact@v4  # <--- اینو از v3 بکن v4
        with:
          name: TWRP-Samsung-A145P
          path: workspace/out/target/product/a145p/recovery.img

